version: '2'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bridge

  redis-client:
    image: redis:latest
    container_name: redis-client
    entrypoint: redis-cli
    depends_on:
      - redis
    stdin_open: true
    tty: true
    networks:
      - bridge

  go-app:
    container_name: go-app
    build: 
      context: ./go-server
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8080:8080"  
    volumes:
      - ./go-server:/app  
    environment:
      - GO_ENV=production  
    networks:
      - bridge

  angular-app:
    container_name: angular-app
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    depends_on:
      - go-app
    ports:
      - "4200:4200"
    volumes:
      - ./angular-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Necessário para detectar mudanças no código em sistemas de arquivos montados
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
    networks:
      - bridge

volumes:
  redis-data:

networks:
  bridge:
    driver: bridge
