version: '2'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bridge

  redis-client:
    image: redis:latest
    container_name: redis-client
    entrypoint: redis-cli
    depends_on:
      - redis
    stdin_open: true
    tty: true
    networks:
      - bridge
  go-app:
    build: .
    container_name: tiny-url
    ports:
      - "8080:8080"  # Mapeando a porta 8080 do container para a máquina host
    volumes:
      - .:/app  # Monta o diretório atual no container (útil para desenvolvimento)
    environment:
      - GO_ENV=production  # Defina qualquer variável de ambiente que seu app precise
    networks:
      - bridge

volumes:
  redis-data:
networks:
  bridge:
    driver:
      bridge

